### ISSUE TITLE
Error when update.py is used

### ISSUE THREAD

**Issue by zaffre45** [pdinklag/MinecraftStats#128]
Traceback (most recent call last):
  File "update.py", line 43, in <module>
    merge_dict(configJson, json.load(configFile))
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 17 (char 82)

I'm not sure where to go from here.

**Comment by pdinklag** [comment]
Since you already closed it, did you figure it out?
It appears that you fed it an invalid config JSON file. In that case, I'm sure a more human readable error message would be helpful.
