### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: net/skinsrestorer/api/SkinsRestorerAPI

### ISSUE THREAD

**Issue by wling-art** [pdinklag/MinecraftStats#240]
[08:37:09] [Craft Scheduler Thread - 12 - MinecraftStats/WARN]: [MinecraftStats] Plugin MinecraftStats v3.2.1 generated an exception while executing task 1049
java.lang.NoClassDefFoundError: net/skinsrestorer/api/SkinsRestorerAPI
	at de.pdinklag.mcstats.bukkit.SkinsRestorerProfileProvider.<init>(SkinsRestorerProfileProvider.java:15) ~[[M][WEB统计]MinecraftStats.jar:?]
	at de.pdinklag.mcstats.bukkit.BukkitUpdater.getAuthenticProfileProvider(BukkitUpdater.java:47) ~[[M][WEB统计]MinecraftStats.jar:?]
	at de.pdinklag.mcstats.Updater.run(Updater.java:352) ~[[M][WEB统计]MinecraftStats.jar:?]
	at de.pdinklag.mcstats.bukkit.BukkitUpdater.run(BukkitUpdater.java:71) ~[[M][WEB统计]MinecraftStats.jar:?]
	at de.pdinklag.mcstats.bukkit.BukkitUpdateTask.run(BukkitUpdateTask.java:17) ~[[M][WEB统计]MinecraftStats.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.skinsrestorer.api.SkinsRestorerAPI
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 11 more

**Comment by pdinklag** [comment]
I'm gonna need more info here. I suppose you have Skins Restorer installed, but looks like you're using a version *MinecraftStats* doesn't support for some reason.

What version of Skins Restorer are you using?

**Comment by wling-art** [comment]
> 是一个没有 API 的版本。在较新的版本中，旧的或重大的更改。
> 
> 您使用的是哪个版本的

latest: 15.0.6

I think it's the new version of SkinsRestorerAPI's API but the plugin isn't adapted, right?

**Comment by pdinklag** [comment]
> > 是一个没有 API 的版本。在较新的版本中，旧的或重大的更改。
> > 您使用的是哪个版本的
> 
> latest: 15.0.6
> 
> I think it's the new version of Skins Restorer API but the plugin isn't adapted, right?

I didn't adapt anything.

Apparently, according to their [documentation](https://jd.skinsrestorer.net/net/skinsrestorer/api/SkinsRestorer.html), they changed the class name from `SkinsRestorerAPI` to just `SkinsRestorer`. That is *horrible* project management on their side...

But thank you for noting, I will have to adapt *MinecraftStats* for it.

**Comment by wling-art** [comment]
> > > 是一个没有 API 的版本。在较新的版本中，旧的或重大的更改。
> > > 您使用的是哪个版本的
> > 
> > 
> > 最新版本：15.0.6
> > 我认为这是 Skins Restorer API 的新版本，但插件没有改编，对吧？
> 
> 我没有适应任何东西。
> 
> 显然，根据他们的[文档](https://jd.skinsrestorer.net/net/skinsrestorer/api/SkinsRestorer.html)，他们将类名从 更改为 just .我不知道他们_什么时候_改变的。这对他们来说是非常不幸的项目管理，这些更改破坏了所有使用 API 的插件，并使支持不同版本变得不必要地复杂......`SkinsRestorerAPI``SkinsRestorer`
> 
> 但感谢您的注意，我将不得不为此调整 _MinecraftStats_。

Oh yeah, I really don't know which nerve in their head is twitching, they've harmed a lot of plugins with their updates.

**Comment by Athar42** [comment]
I'm doing a little "bump" on this one, as it seems to not be published yet... so I still post my log output just in case, but seems the same as the original author : 

```
[23:14:14 WARN]: [MinecraftStats] Plugin MinecraftStats v3.3.0 generated an exception while executing task 64
java.lang.NoClassDefFoundError: net/skinsrestorer/api/SkinsRestorerAPI
        at de.pdinklag.mcstats.bukkit.SkinsRestorerProfileProvider.<init>(SkinsRestorerProfileProvider.java:15) ~[MinecraftStats-3.3.0.jar:?]
        at de.pdinklag.mcstats.bukkit.BukkitUpdater.getAuthenticProfileProvider(BukkitUpdater.java:47) ~[MinecraftStats-3.3.0.jar:?]
        at de.pdinklag.mcstats.Updater.run(Updater.java:368) ~[MinecraftStats-3.3.0.jar:?]
        at de.pdinklag.mcstats.bukkit.BukkitUpdater.run(BukkitUpdater.java:71) ~[MinecraftStats-3.3.0.jar:?]
        at de.pdinklag.mcstats.bukkit.BukkitUpdateTask.run(BukkitUpdateTask.java:17) ~[MinecraftStats-3.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.skinsrestorer.api.SkinsRestorerAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more
```

Using :
- Paper 1.20.4 build 497 (latest from this branch)
- MinecraftStats 3.3.0 (also latest so :) )
- SkinRestorer 15.0.15
```
[23:16:24 INFO]: [SkinsRestorer] ----------------------------------------------
[23:16:24 INFO]: [SkinsRestorer]     +==================+
[23:16:24 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[23:16:24 INFO]: [SkinsRestorer]     |------------------|
[23:16:24 INFO]: [SkinsRestorer]     |    Proxy Mode    |
[23:16:24 INFO]: [SkinsRestorer]     +==================+
[23:16:24 INFO]: [SkinsRestorer] ----------------------------------------------
[23:16:24 INFO]: [SkinsRestorer]     Version: 15.0.15
[23:16:24 INFO]: [SkinsRestorer]     Commit: fcfa8b9
[23:16:24 INFO]: [SkinsRestorer]     This is the latest version!
[23:16:24 INFO]: [SkinsRestorer] ----------------------------------------------
```


Is there any estimation on when a new build including the fix will be out ? (sorry for the ping @pdinklag )

Thanks :)

**Comment by Athar42** [comment]
From my testing so far, the error is still displayed, because the API isn't working when the server is in "Proxy Mode"

> Make sure SkinsRestorer is not in "Proxy Mode" if you are using BungeeCord/Velocity.

So, there should be a check to wether enable or not the SkinsRestorer support depending on the functioning mode of it.

**Comment by pdinklag** [comment]
Build 3.3.1 is now released.

> From my testing so far, the error is still displayed, because the API isn't working when the server is in "Proxy Mode"

I have genuinely no idea what this means. What is "Proxy Mode"? In any event, if SkinsRestorer doesn't work in "Proxy Mode", then why not *not* use it in "Proxy Mode"? Why would I fix something in MinecraftStats for SkinsRestorer for a scenario in which SkinsRestorer is not even supposed to work?

**Comment by Athar42** [comment]
The "Proxy mode" is used, in general, when you use... a proxy :D (sorry^^, like Velocity).

For example, this is from my Proxy (Velocity server) : 
![image](https://github.com/pdinklag/MinecraftStats/assets/44590042/eebc743c-b1d4-41be-abb8-324c5cf5850a)

And on one of my backend server (lobby, creative, or any other, that's the same) : 
![image](https://github.com/pdinklag/MinecraftStats/assets/44590042/441b6b86-740f-4fae-a9f4-fcd5e8a9c90c)


And for "SR is not even supposed to work", well, it work in Proxy Mode (it's part of its job), but the API itself, in such mode, it's not : 
https://skinsrestorer.net/docs/development/api#getting-issues

> Make sure SkinsRestorer is not in "Proxy Mode" if you are using BungeeCord/Velocity.

And just in case you wonder "Why" I'm in proxy mode, that's the intended setup for when you use a proxy : 
https://skinsrestorer.net/docs/installation/velocity


So sadly, SR didn't made it easy for developpers, they have to check in which state this plugin is and, if in "Proxy Mode", disable this (or the users, like me, should enable the "Backend API", but the player skin is not retrieved this way, don't know why. At least, the error just vanish)

**Comment by pdinklag** [comment]
> From my testing so far, the error is still displayed, because the API isn't working when the server is in "Proxy Mode"

To get back to this, are you sure it's exactly the same error? Because the error was that the class was not found, and that's because they renamed it. I updated MinecraftStats to use the new class name, so if there's still an error message, it should really be a different one? Can you post it?

> The "Proxy mode" is used, in general, when you use... a proxy :D (sorry^^, like Velocity).

But if a server is a proxy, doesn't it mean it just forwards connections to another server or somehow shares data with another server? I don't really understand why you would set up a statistics framework for a proxy - do you set up MinecraftStats for *every* proxy?

Could you try [aggregating stats from multiple servers instead](https://github.com/pdinklag/MinecraftStats?tab=readme-ov-file#combining-multiple-servers-bungeecord)?

**Comment by Athar42** [comment]
I did some "paint skill" :D maybe that'll help in understanding my setup : 
![image](https://github.com/user-attachments/assets/fc10646c-d59b-40d0-b34c-cef304b3acfb)

So, the users connect to the proxy and get redirected to the lobby, then they connect to any "GAME" server they want to access.
Once they are in a "GAME" server, they aren't connected to the lobby anymore, only through the proxy.


MinecraftStats isn't installed on all of the "GAME" server, just a couple of those.
And "SkinRestorer" is, indeed, installed on ALL the servers, proxy included.

So, for SkinRestorer, it's working on my proxy as "a main thread", and all sub-server (Lobby and GAME x) are connected in proxy mode (as you can see in my previous post).
In that case, all "sub servers" connect to the proxy to get SkinRestorer datas.

For that specific scenario, you have to enable SR to use an SQL database so that all servers are in sync for the datas.


Anyways, that's not of a big deal, as the only "breaking" stuff I saw is not getting the proper skin of the player (that's sad, but we can live without it 😊)

As you open the change #255 , just get rid of it, that's fine I think.

Your plugin will still rocks without it 😋
