### ISSUE TITLE
Error on new CLI

### ISSUE THREAD

**Issue by cunhar** [pdinklag/MinecraftStats#250]
failed to write database
java.lang.NullPointerException
        at de.pdinklag.mcstats.Updater.lambda$run$23(Updater.java:692)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at de.pdinklag.mcstats.Updater.run(Updater.java:691)
        at de.pdinklag.mcstats.cli.CLIUpdater.run(CLIUpdater.java:65)
        at de.pdinklag.mcstats.cli.MinecraftStatsCLI.main(MinecraftStatsCLI.java:45)

**Comment by cunhar** [comment]
i updated from [v3.3.0](https://github.com/pdinklag/MinecraftStats/releases/tag/v3.3.0) to [v3.3.1](https://github.com/pdinklag/MinecraftStats/releases/tag/v3.3.1) and now get this error

**Comment by pdinklag** [comment]
From a quick look I cannot tell what's wrong, none of the involved variables should ever become `null`. I will try to add some more logging here in the scope of #251 so we can see what's going on. Until then, I suggest you downgrade to 3.3.0.

(The time gap between 3.3.1 and the next release will not be that long)

**Comment by cunhar** [comment]
@pdinklag you lied to me
