### ISSUE TITLE
Bug: SkinsRestorerAPI is not initialized yet

### ISSUE THREAD

**Issue by wling-art** [pdinklag/MinecraftStats#254]
``` java
[05:14:24 INFO]: [MinecraftStats] Loading server plugin MinecraftStats v3.3.1
[05:14:24 INFO]: [MinecraftStats] Enabling MinecraftStats v3.3.1
[05:14:24 INFO]: [MinecraftStats] Exporting to auto-detected webserver document root: /opt/mcsmanager/daemon/data/InstanceData/adb895f262a9460ca89cc827ef0a91d9/./bluemap/web
[05:14:25 INFO]: [MinecraftStats] Using SkinsRestorer v15.3.0
[05:14:25 WARN]: [MinecraftStats] failed to retrieve SkinsRestorer API -- defaulting to Mojang
java.lang.IllegalStateException: SkinsRestorerAPI is not initialized yet! (Are you trying to access it without softDepends?)
        at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerProvider.get(SkinsRestorerProvider.java:35)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.SkinsRestorerProfileProvider.<init>(SkinsRestorerProfileProvider.java:19)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdater.getAuthenticProfileProvider(BukkitUpdater.java:48)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.Updater.run(Updater.java:369)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdater.run(BukkitUpdater.java:75)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdateTask.run(BukkitUpdateTask.java:17)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[05:14:25 INFO]: [MinecraftStats] Web frontend updated.
[05:19:25 WARN]: [MinecraftStats] failed to retrieve SkinsRestorer API -- defaulting to Mojang
java.lang.IllegalStateException: SkinsRestorerAPI is not initialized yet! (Are you trying to access it without softDepends?)
        at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerProvider.get(SkinsRestorerProvider.java:35)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.SkinsRestorerProfileProvider.<init>(SkinsRestorerProfileProvider.java:19)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdater.getAuthenticProfileProvider(BukkitUpdater.java:48)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.Updater.run(Updater.java:369)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdater.run(BukkitUpdater.java:75)
        at MinecraftStats_v3.3.1.jar//de.pdinklag.mcstats.bukkit.BukkitUpdateTask.run(BukkitUpdateTask.java:17)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by pdinklag** [comment]
MinecraftStats *does* list Skins Restorer as a soft dependency, so I'm not really sure what to do.

You only showed part of the log. When is a message like `Enabling SkinsRestorer v15.3.0` printed? Before this error?

**Comment by wling-art** [comment]
I'm sure it's in every
[MinecraftStats] Web frontend updated.
I'm sure it's every time [MinecraftStats] Web frontend updated.

**Comment by pdinklag** [comment]
True. Well, the error message is bogus, because obviously Skins Restorer *has* been initialized.
Can you find a message like `Enabling SkinsRestorer v15.3.0` in your logfile? It should be somewhere at the beginning.

In any event, I don't think there will be much I can do here. I am using the Skins Restorer API [as they show it in their example](https://github.com/SkinsRestorer/SkinsRestorerAPIExample/blob/fdfd0d132d3a33e7427814e3ff174b8d801a72f6/src/main/java/net/skinsrestorer/apiexample/SkinsRestorerAPIExample.java#L47). Since that does not work, it must be a bug in Skins Restorer.

**Comment by wling-art** [comment]
I updated their plugin to 15.4.1 and found that I don't get this problem anymore, turns out it was their problem, misunderstood.
